language: python
python: '2.6'
env:
  global:
  - secure: Ni1opL+3wD8A2qBcFUZ9oY8zeblloyPy/LFb981qFQsGAXWwDnaa7i/2yxQXFXP2ahTUojflp7icDvBwWpV8Tc48JMJDOQLvxSaijiSpYdzx4m1FLXufv7kdgeuvYsLcBk4+vhqPTZaX4JADubj0V+/AJThupYG9XF5r3LfU2DjgRwxpRQthShgb81cKTMVYqdhq4/A533SFLuYVou/PlkywYNcwp9QHVI8bzw8XlRPkzJoPcH2871yfOofQgQp7l96cFbEXhU027y3sBDKzz/Rm/pEysw71EyPqlJiZxn5rHwhXcv0eZ8KcwxZ5c6bPh1rDYYj5CxRqzXXuHRL60Hvwfd6FiWAb4tZo3NNDYamc1yDq4pLdkKHGqmhf44cNBcCegs4Myn2WKUt/dSWegoHvBlZNxNWcirBLxOQbfvTyEqJ60Hh5FBWtG0hCNMio4bUmWm47w6SzucCpzIe4gENqQ9d++ObskpQ9fFrJsW1qPcHDOZzpg/0aHhd4QN61a0ycQMd2g6USlzmjjZSFVXmbu11kWKbADP/QhSmpiKoXiFY1sYvo3IGKYZaj9PxiucGtpGynplFgE006ymf2v70evjrY+FmUdFX353w0wefOFCmx3Ukx9T16YwNn8CuZDIW3Jdx5zhzl8lomF7FuLH7SUTK2xoQiHkQBnaM3B/I=
  - secure: YD8QucufBppGWj9yKYvdDGKD5fFOE6H7xHYfSCpRbSdvMlOu5WAuuoCr+ie6GonZse+fqRidWdOOTxgtjqSAxR76wal2DaCPXwW+XHCjDOylYtmDpI33bwibXvc9hB83w/2CNuzrNeeTTqKjh6QzAlgJ5e9sHVSG04u4uF4qIxVAxkygHmetrPofSsUMJXkJ6Vdz4MYcIccw+pT7DiSGgNGnv/KPES1bSGCjS2Tj8jRYt7583WkL41BX7Atmnzk7/sM9B/hIv+m1xyLShao8UaPdbTVJl5LMKI20NXZXkUWwWvYrzMZ6Xi2O83lce8YnLYBk37n7A/YXux9vT818TYUcXrpab0qhBal67+L1c4m/2iDRYq5L+pPkjw9ftslN5zR8gqBN6c/ZTf0QSrNmtUjr8dyFKgVjFAMYb4Rth0yJReU6O/xFyyj4rFOUTjESYviCN9Dxj5Spznx2S4ayuIIXBAhDKYTDG0vQOQbdBeOiuwkqh/y63/XPihPxwuXPO1QpzrJGFiEgtmv21mHOr2pX2t9IlKJcDbRLHUAjzptbjDej+gdO7s1xe1+8kwRgiU+LuxzzviNSY9rmQTfIlJRRUvElkPyxCGmSE6DMVMpNrxQiHLJ5SoBeEP6RE00Wlk2qk9TOLIoNPowGa3sxEOYOsGDlmaIxurduat9rsAY=
install:
  - pip install MySQL-python

script: 
  - cp server/config_example.py server/config.py
  - python server/next.cgi

before_deploy:
  - rm server/config.py
  - npm install gulp
  - npm install gulp -g
  - npm install vinyl-ftp gulp-util minimist --save-dev
  - chmod +x deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh  $FTP_USER  $FTP_PASSWORD  $TRAVIS_TAG"
  on:
    tags: true
