language: python
python: '2.6'
env:
  global:
  - secure: Ni1opL+3wD8A2qBcFUZ9oY8zeblloyPy/LFb981qFQsGAXWwDnaa7i/2yxQXFXP2ahTUojflp7icDvBwWpV8Tc48JMJDOQLvxSaijiSpYdzx4m1FLXufv7kdgeuvYsLcBk4+vhqPTZaX4JADubj0V+/AJThupYG9XF5r3LfU2DjgRwxpRQthShgb81cKTMVYqdhq4/A533SFLuYVou/PlkywYNcwp9QHVI8bzw8XlRPkzJoPcH2871yfOofQgQp7l96cFbEXhU027y3sBDKzz/Rm/pEysw71EyPqlJiZxn5rHwhXcv0eZ8KcwxZ5c6bPh1rDYYj5CxRqzXXuHRL60Hvwfd6FiWAb4tZo3NNDYamc1yDq4pLdkKHGqmhf44cNBcCegs4Myn2WKUt/dSWegoHvBlZNxNWcirBLxOQbfvTyEqJ60Hh5FBWtG0hCNMio4bUmWm47w6SzucCpzIe4gENqQ9d++ObskpQ9fFrJsW1qPcHDOZzpg/0aHhd4QN61a0ycQMd2g6USlzmjjZSFVXmbu11kWKbADP/QhSmpiKoXiFY1sYvo3IGKYZaj9PxiucGtpGynplFgE006ymf2v70evjrY+FmUdFX353w0wefOFCmx3Ukx9T16YwNn8CuZDIW3Jdx5zhzl8lomF7FuLH7SUTK2xoQiHkQBnaM3B/I=
  - secure: YD8QucufBppGWj9yKYvdDGKD5fFOE6H7xHYfSCpRbSdvMlOu5WAuuoCr+ie6GonZse+fqRidWdOOTxgtjqSAxR76wal2DaCPXwW+XHCjDOylYtmDpI33bwibXvc9hB83w/2CNuzrNeeTTqKjh6QzAlgJ5e9sHVSG04u4uF4qIxVAxkygHmetrPofSsUMJXkJ6Vdz4MYcIccw+pT7DiSGgNGnv/KPES1bSGCjS2Tj8jRYt7583WkL41BX7Atmnzk7/sM9B/hIv+m1xyLShao8UaPdbTVJl5LMKI20NXZXkUWwWvYrzMZ6Xi2O83lce8YnLYBk37n7A/YXux9vT818TYUcXrpab0qhBal67+L1c4m/2iDRYq5L+pPkjw9ftslN5zR8gqBN6c/ZTf0QSrNmtUjr8dyFKgVjFAMYb4Rth0yJReU6O/xFyyj4rFOUTjESYviCN9Dxj5Spznx2S4ayuIIXBAhDKYTDG0vQOQbdBeOiuwkqh/y63/XPihPxwuXPO1QpzrJGFiEgtmv21mHOr2pX2t9IlKJcDbRLHUAjzptbjDej+gdO7s1xe1+8kwRgiU+LuxzzviNSY9rmQTfIlJRRUvElkPyxCGmSE6DMVMpNrxQiHLJ5SoBeEP6RE00Wlk2qk9TOLIoNPowGa3sxEOYOsGDlmaIxurduat9rsAY=
  - secure: kRB6CBLVlCHFc9u3UdwFe62AA3Z3zX0sUxuH1EYi2eqfJtoXmkEN+jkWU9hNkG7A6bDJnaH+l6ND3yP48I59guggeZj6e25uUJ7c518lCHsb5LVJwLbu5YLAUXx4T7yB1a4VxthsRc1WpIcZJJYguNfroT/8IslhfVCu70OXc/1JT+23OInSHQXfUxCqkgRvOcHAp3aRT5mWUsbXSCW8EYuSG/u+Rn3fCKxMDjG4LBt+C6PFyvHParQ0XKWwiNc6asQAU0LpTVc4VGm4x+MvOTnuJUVC+XeycHaafg8FJ1PsgoDpS0bC2QE91LrbmHnIPd1U3iCFMkFYy6r7Hi2S6/OCHjyjIEuiv06fLpBDZiiBYZ1l1RrQDkI5BzmE9QNCIJEcYTnvc4qy252MzHhIC0e/U+RR+FLD0e+b81vx4AxBIxS9PdlalrkFh+qLGkPuEbX0p30sxW7imiXcJSJ6hTocHsU0aGIjLm2Gu/flrQjiDBLqW6IqVt9UtkmamWkuWTkFCVW+L16lL14zP42L1CEFoJRdxv6ivhixsrH2FvgOKS8kMohg+lxK3I2Pm+0nS75QjK28i+iJibbQTBhzE6Fi+OdVI5W8GrZARcU2rmzD15nvx3E3A35hBWIVotU3cguDdRiYu31eFsQFySUMGPh5P2yz/d/lD7yGgxSlDqY=
  - secure: i/BdxLwGnTofLSzb6dKpvD092DvfyP4uVOSv5MO+CLwaZqeGD4bDpCUfeTqiwNbqPjFoagEb0z2OmH2El4nU/vS7pgJ1BUzXtslE8MU71Kw7ZXD7JsHdpKbWN2O9gdftiDygM+g+reyx95Y7nujklCSZv0MaxzzwD/tdia00SvFQBo49EVzq47EOuZAG2XYEuOW4Duxu1iVxrjIM8U90ReyjMlCPKD2ail9+p7lKj8zA18EgwnKUd4H+5+4RXetncXgwAkUZ0R3TP/LTfJIxyQcs2WjHQlcU2xaXOFepgN6NcYcpbOcJ2iXjV+FwJubGrk6zvA439fp5XAEQB1aiT1b8kom9zdorXXnR4W3ux96pp29fR5B8k4OG1ZGFijtPgJgDsawAokeWXPMnM0Tz07MyDCj8o0Pvsc4EaghWdLsmgH+8DzprP2K7ru3UGurmtWUzOJhHhI//iXB7y0sAKKGURzfuNLqKWWfpQNmPTTJ3jW9MFYyP/7jc09T5Bl1uODd+eppRt1G4+UWXGNS9dzszJCEQaEbZF9eLoO3vceXvs991BLo9mARYUD5jD8VDYk40My1ON4N684eMKz00s6PPfnS+l3pbrc9kM4u3Pe0EdJ1vdjYDVpWTipqdaz9E7JO06P8MWJZInqos/7x8NW8/nEaXlaWQD6EHj1fj50c=
install:
- pip install MySQL-python
script:
- cp server/config_example.py server/config.py
- python server/next.cgi
- npm install gulp
- npm install gulp -g
- npm install vinyl-ftp gulp-util minimist --save-dev
- chmod +x staging.sh
- "./staging.sh  $FTP_USER  $STAGING_FTP_PASSWORD"
before_deploy:
- rm server/config.py
- chmod +x deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh  $FTP_USER  $FTP_PASSWORD  $TRAVIS_TAG"
  on:
    tags: true
